# TMDB Reminder task runner. Run `just` to list recipes.

set dotenv-load
set shell := ["bash", "-euo", "pipefail", "-c"]

# Disposable PostgreSQL used by the backend integration tests.
export DATABASE_URL_TEST := "postgresql+psycopg://tmdb:tmdb@localhost:55432/tmdb_reminder"
test_db_container := "tmdb-reminder-testdb"

# Show all recipes.
default:
    @just --list

# --- Backend ---------------------------------------------------------------

# Install backend dependencies (locked).
[working-directory('backend')]
backend-install:
    uv sync --frozen

# Format check + lint + type-check.
[working-directory('backend')]
backend-lint:
    uv run ruff format --check .
    uv run ruff check .
    uv run mypy

# Auto-fix formatting and lint issues.
[working-directory('backend')]
backend-fix:
    uv run ruff format .
    uv run ruff check --fix .

# Run the backend test suite (integration tests need the test DB up).
[working-directory('backend')]
backend-test *args:
    uv run pytest {{ args }}

# Regenerate the committed OpenAPI artifact (frontend/openapi.json).
[working-directory('backend')]
openapi:
    uv run python scripts/export_openapi.py

# Apply migrations, then assert the models and schema have not drifted.
[working-directory('backend')]
migrate-check:
    DATABASE_URL={{ DATABASE_URL_TEST }} uv run alembic upgrade head
    DATABASE_URL={{ DATABASE_URL_TEST }} uv run alembic check

# Create a new autogenerated migration: `just migrate-new "add x"`.
[working-directory('backend')]
migrate-new message:
    DATABASE_URL={{ DATABASE_URL_TEST }} uv run alembic revision --autogenerate -m "{{ message }}"

# Run the API locally (needs a reachable database).
[working-directory('backend')]
run-api:
    uv run tmdb-reminder-api

# Run the scheduler worker locally.
[working-directory('backend')]
run-worker:
    uv run tmdb-reminder-worker

# --- Frontend --------------------------------------------------------------

# Install frontend dependencies (locked).
[working-directory('frontend')]
frontend-install:
    bun install --frozen-lockfile

# Regenerate the typed API client from frontend/openapi.json.
[working-directory('frontend')]
gen-api:
    bun run gen:api

# Lint + type-check + unit tests.
[working-directory('frontend')]
frontend-check:
    bun run lint
    bun run typecheck
    bun run test

# Production build.
[working-directory('frontend')]
frontend-build:
    bun run build

# Playwright end-to-end flow (Chromium, intercepted APIs).
[working-directory('frontend')]
e2e:
    bun run e2e

# Run the Vite dev server.
[working-directory('frontend')]
dev:
    bun run dev

# --- Integration test database --------------------------------------------

# Start a throwaway PostgreSQL for integration tests (port 55432).
test-db-up:
    -docker rm -f {{ test_db_container }}
    docker run -d --rm --name {{ test_db_container }} -e POSTGRES_USER=tmdb -e POSTGRES_PASSWORD=tmdb -e POSTGRES_DB=tmdb_reminder -p 127.0.0.1:55432:5432 postgres:18-alpine
    @echo "waiting for postgres..."
    @for attempt in $(seq 1 30); do if docker exec {{ test_db_container }} pg_isready -U tmdb >/dev/null 2>&1; then exit 0; fi; sleep 1; done; echo "postgres did not become ready within 30 seconds" >&2; exit 1
    @echo "ready on 55432"

# Stop the throwaway test database.
test-db-down:
    -docker rm -f {{ test_db_container }}

# Full backend suite against a fresh test database.
backend-test-full: test-db-up && test-db-down
    just migrate-check
    just backend-test -q

# --- Docker Compose --------------------------------------------------------

# Pull the published images and start the full stack (reads .env).
# Set IMAGE_TAG in .env to select a sha-<short-commit> or v<version> tag.
up:
    docker compose up -d --pull always

# Stop the stack while preserving PostgreSQL data.
down:
    docker compose down

# Stop the stack and permanently remove PostgreSQL data.
[confirm("Permanently remove the Docker Compose database volume?")]
down-volumes:
    docker compose down -v

# Follow logs (optionally for one service: `just logs api`).
logs *service:
    docker compose logs -f {{ service }}

# Validate the compose file.
compose-config:
    docker compose config --quiet

# Build both Dockerfiles locally (same contexts CI uses; does not push).
docker-build:
    docker build ./backend
    docker build ./frontend

# --- Aggregate -------------------------------------------------------------

# Everything CI checks locally. This starts and removes a disposable test DB.
check: backend-lint openapi gen-api frontend-check backend-test-full frontend-build e2e compose-config docker-build
    git diff --exit-code -- frontend/openapi.json frontend/src/api/schema.ts
    @echo "all checks passed"
