"""Integration test: Alembic upgrade applies cleanly and matches the models.

Runs against a throwaway database so it never disturbs the shared test schema.
"""

from __future__ import annotations

import os

import psycopg
from alembic import command
from alembic.config import Config
from sqlalchemy.engine import make_url

from conftest import TEST_DSN, integration

pytestmark = integration

SCRATCH_DB = "tmdb_reminder_migtest"


def _admin_conn_kwargs(dsn: str) -> dict:
    url = make_url(dsn)
    return {
        "host": url.host,
        "port": url.port,
        "user": url.username,
        "password": url.password,
        "dbname": "postgres",
    }


def _scratch_dsn(dsn: str) -> str:
    return make_url(dsn).set(database=SCRATCH_DB).render_as_string(hide_password=False)


def test_alembic_upgrade_and_no_drift():
    assert TEST_DSN is not None
    admin = _admin_conn_kwargs(TEST_DSN)
    with psycopg.connect(autocommit=True, **admin) as conn:
        conn.execute(f'DROP DATABASE IF EXISTS "{SCRATCH_DB}" WITH (FORCE)')
        conn.execute(f'CREATE DATABASE "{SCRATCH_DB}"')

    previous = os.environ.get("DATABASE_URL")
    os.environ["DATABASE_URL"] = _scratch_dsn(TEST_DSN)
    try:
        cfg = Config("alembic.ini")
        command.upgrade(cfg, "head")
        # command.check raises AutogenerateDiffsDetected if models drift from schema.
        command.check(cfg)
    finally:
        if previous is None:
            os.environ.pop("DATABASE_URL", None)
        else:
            os.environ["DATABASE_URL"] = previous
        with psycopg.connect(autocommit=True, **admin) as conn:
            conn.execute(f'DROP DATABASE IF EXISTS "{SCRATCH_DB}" WITH (FORCE)')
