"""Integration test: Alembic upgrade applies cleanly and matches the models.

Runs against a throwaway database so it never disturbs the shared test schema.
"""

from __future__ import annotations

import os
from datetime import date

import psycopg
import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy.engine import make_url

from conftest import TEST_DSN, integration

pytestmark = integration

SCRATCH_DB = "tmdb_reminder_migtest"


def _conn_kwargs(dsn: str, database: str) -> dict:
    url = make_url(dsn)
    return {
        "host": url.host,
        "port": url.port,
        "user": url.username,
        "password": url.password,
        "dbname": database,
    }


def _scratch_dsn(dsn: str) -> str:
    return make_url(dsn).set(database=SCRATCH_DB).render_as_string(hide_password=False)


def test_alembic_upgrade_and_no_drift():
    assert TEST_DSN is not None
    admin = _conn_kwargs(TEST_DSN, "postgres")
    scratch = _conn_kwargs(TEST_DSN, SCRATCH_DB)
    with psycopg.connect(autocommit=True, **admin) as conn:
        conn.execute(f'DROP DATABASE IF EXISTS "{SCRATCH_DB}" WITH (FORCE)')
        conn.execute(f'CREATE DATABASE "{SCRATCH_DB}"')

    previous = os.environ.get("DATABASE_URL")
    os.environ["DATABASE_URL"] = _scratch_dsn(TEST_DSN)
    try:
        cfg = Config("alembic.ini")
        command.upgrade(cfg, "f6580ed33e22")
        with psycopg.connect(**scratch) as conn:
            conn.execute(
                """
                INSERT INTO tracked_titles
                    (id, media_type, tmdb_id, title, status, created_at, updated_at)
                VALUES
                    (1, 'movie', 603, 'The Matrix', 'active', NOW(), NOW())
                """
            )
        # available_since exists after b47e2c9a1f30; seed a dated row for backfill.
        command.upgrade(cfg, "b47e2c9a1f30")
        with psycopg.connect(**scratch) as conn:
            conn.execute(
                """
                INSERT INTO tracked_titles
                    (id, media_type, tmdb_id, title, status, available_since,
                     created_at, updated_at)
                VALUES
                    (2, 'movie', 604, 'Dune', 'completed', DATE '2026-01-01', NOW(), NOW())
                """
            )
        command.upgrade(cfg, "head")
        with psycopg.connect(**scratch) as conn:
            row1 = conn.execute(
                "SELECT title, available_since, availability_source "
                "FROM tracked_titles WHERE id = 1"
            ).fetchone()
            row2 = conn.execute(
                "SELECT title, available_since, availability_source "
                "FROM tracked_titles WHERE id = 2"
            ).fetchone()
        # Undated row stays unknown; dated row is backfilled as release_date.
        assert row1 == ("The Matrix", None, None)
        assert row2 == ("Dune", date(2026, 1, 1), "release_date")

        # Availability invariants: source is coupled to available_since.
        with psycopg.connect(autocommit=True, **scratch) as conn:
            # watch_provider must not carry a date.
            with pytest.raises(psycopg.errors.CheckViolation):
                conn.execute(
                    "INSERT INTO tracked_titles (id, media_type, tmdb_id, title, status, "
                    "available_since, availability_source, created_at, updated_at) VALUES "
                    "(3, 'movie', 605, 'X', 'completed', DATE '2026-02-01', "
                    "'watch_provider', NOW(), NOW())"
                )
            # release_date requires a date.
            with pytest.raises(psycopg.errors.CheckViolation):
                conn.execute(
                    "INSERT INTO tracked_titles (id, media_type, tmdb_id, title, status, "
                    "available_since, availability_source, created_at, updated_at) VALUES "
                    "(4, 'movie', 606, 'Y', 'completed', NULL, 'release_date', NOW(), NOW())"
                )
            # Undated watch_provider availability is valid.
            conn.execute(
                "INSERT INTO tracked_titles (id, media_type, tmdb_id, title, status, "
                "available_since, availability_source, created_at, updated_at) VALUES "
                "(5, 'movie', 607, 'Z', 'completed', NULL, 'watch_provider', NOW(), NOW())"
            )
        # command.check raises AutogenerateDiffsDetected if models drift from schema.
        command.check(cfg)
    finally:
        if previous is None:
            os.environ.pop("DATABASE_URL", None)
        else:
            os.environ["DATABASE_URL"] = previous
        with psycopg.connect(autocommit=True, **admin) as conn:
            conn.execute(f'DROP DATABASE IF EXISTS "{SCRATCH_DB}" WITH (FORCE)')
