/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_v1_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status/gotify-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gotify Test */
        post: operations["gotify_test_api_v1_status_gotify_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracked-titles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tracked */
        get: operations["list_tracked_api_v1_tracked_titles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracked-titles/{media_type}/{tmdb_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Track Title */
        put: operations["track_title_api_v1_tracked_titles__media_type___tmdb_id__put"];
        post?: never;
        /** Stop Title */
        delete: operations["stop_title_api_v1_tracked_titles__media_type___tmdb_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConfigStatus */
        ConfigStatus: {
            /** App Timezone */
            app_timezone: string;
            /** Gotify Configured */
            gotify_configured: boolean;
            /** Gotify Priority */
            gotify_priority: number;
            /** Reminder Time */
            reminder_time: string;
            /** Tmdb Configured */
            tmdb_configured: boolean;
            /** Tmdb Language */
            tmdb_language: string;
            /** Tmdb Region */
            tmdb_region: string;
        };
        /**
         * EventKind
         * @enum {string}
         */
        EventKind: "movie_digital" | "tv_episode";
        /** GotifyTestResponse */
        GotifyTestResponse: {
            /** Error */
            error?: string | null;
            /** Message Id */
            message_id?: number | null;
            /** Sent */
            sent: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobStatus */
        JobStatus: {
            /** Failure Summary */
            failure_summary?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Job Name */
            job_name: string;
            /** Outcome */
            outcome?: string | null;
            /**
             * Processed Count
             * @default 0
             */
            processed_count: number;
            /** Started At */
            started_at?: string | null;
        };
        /** LivenessResponse */
        LivenessResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /**
         * MediaType
         * @enum {string}
         */
        MediaType: "movie" | "tv";
        /** NextRelease */
        NextRelease: {
            /** Episode Number */
            episode_number?: number | null;
            kind: components["schemas"]["EventKind"];
            /**
             * Scheduled Date
             * Format: date
             */
            scheduled_date: string;
            /** Season Number */
            season_number?: number | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Page */
            page: number;
            /** Results */
            results: components["schemas"]["SearchResultItem"][];
            /** Total Pages */
            total_pages: number;
            /** Total Results */
            total_results: number;
        };
        /** SearchResultItem */
        SearchResultItem: {
            /** Available Since */
            available_since?: string | null;
            media_type: components["schemas"]["MediaType"];
            next_release?: components["schemas"]["NextRelease"] | null;
            /** Original Title */
            original_title?: string | null;
            /** Overview */
            overview?: string | null;
            /** Poster Path */
            poster_path?: string | null;
            /** Poster Url */
            poster_url?: string | null;
            /** Release Year */
            release_year?: number | null;
            /** Title */
            title: string;
            /** Tmdb Id */
            tmdb_id: number;
            /** Tmdb Url */
            tmdb_url: string;
            tracking_status?: components["schemas"]["TitleStatus"] | null;
        };
        /** StatusResponse */
        StatusResponse: {
            config: components["schemas"]["ConfigStatus"];
            /** Degraded */
            degraded: boolean;
            /** Gotify Ok */
            gotify_ok?: boolean | null;
            /** Last Jobs */
            last_jobs?: components["schemas"]["JobStatus"][];
            /**
             * Pending Deliveries
             * @default 0
             */
            pending_deliveries: number;
            /**
             * Recent Delivery Errors
             * @default 0
             */
            recent_delivery_errors: number;
            /** Tmdb Ok */
            tmdb_ok?: boolean | null;
            /**
             * Tracked Active
             * @default 0
             */
            tracked_active: number;
            /**
             * Tracked History
             * @default 0
             */
            tracked_history: number;
        };
        /**
         * TitleStatus
         * @enum {string}
         */
        TitleStatus: "active" | "completed" | "stopped";
        /** TitleView */
        TitleView: {
            /** Available Since */
            available_since?: string | null;
            /** Id */
            id: number;
            /** Last Sync At */
            last_sync_at?: string | null;
            /** Last Sync Status */
            last_sync_status?: string | null;
            media_type: components["schemas"]["MediaType"];
            next_release?: components["schemas"]["NextRelease"] | null;
            /** Original Title */
            original_title?: string | null;
            /** Overview */
            overview?: string | null;
            /** Poster Path */
            poster_path?: string | null;
            /** Poster Url */
            poster_url?: string | null;
            /** Release Year */
            release_year?: number | null;
            status: components["schemas"]["TitleStatus"];
            /** Title */
            title: string;
            /** Tmdb Id */
            tmdb_id: number;
            /** Tmdb Url */
            tmdb_url: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TrackedListResponse */
        TrackedListResponse: {
            /** Items */
            items: components["schemas"]["TitleView"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
            /** View */
            view: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query: {
                query: string;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_v1_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    gotify_test_api_v1_status_gotify_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GotifyTestResponse"];
                };
            };
        };
    };
    list_tracked_api_v1_tracked_titles_get: {
        parameters: {
            query?: {
                view?: string;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackedListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_title_api_v1_tracked_titles__media_type___tmdb_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_type: components["schemas"]["MediaType"];
                tmdb_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TitleView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_title_api_v1_tracked_titles__media_type___tmdb_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_type: components["schemas"]["MediaType"];
                tmdb_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TitleView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
