"""initial schema

Revision ID: f6580ed33e22
Revises: 
Create Date: 2026-08-12 16:33:48.237872
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f6580ed33e22'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=20), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('failure_summary', sa.Text(), nullable=True),
    sa.CheckConstraint("job_name IN ('refresh', 'delivery')", name='ck_job_runs_name'),
    sa.CheckConstraint("outcome IS NULL OR outcome IN ('success','partial','failure')", name='ck_job_runs_outcome'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_runs_name_started', 'job_runs', ['job_name', 'started_at'], unique=False)
    op.create_table('tracked_titles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('media_type', sa.String(length=8), nullable=False),
    sa.Column('tmdb_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision_watch_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=16), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.CheckConstraint("last_sync_status IS NULL OR last_sync_status IN ('ok','error')", name='ck_tracked_titles_sync_status'),
    sa.CheckConstraint("media_type IN ('movie', 'tv')", name='ck_tracked_titles_media_type'),
    sa.CheckConstraint("status IN ('active', 'completed', 'stopped')", name='ck_tracked_titles_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_type', 'tmdb_id', name='uq_tracked_titles_identity')
    )
    op.create_index('ix_tracked_titles_refresh', 'tracked_titles', ['status', 'metadata_refreshed_at'], unique=False)
    op.create_index('ix_tracked_titles_status', 'tracked_titles', ['status'], unique=False)
    op.create_table('release_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tracked_title_id', sa.BigInteger(), nullable=False),
    sa.Column('source_event_key', sa.String(length=200), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('movie_digital', 'tv_episode')", name='ck_release_events_kind'),
    sa.CheckConstraint("state IN ('current', 'superseded', 'withdrawn')", name='ck_release_events_state'),
    sa.ForeignKeyConstraint(['tracked_title_id'], ['tracked_titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_event_key', 'revision', name='uq_release_events_revision')
    )
    op.create_index('ix_release_events_current', 'release_events', ['source_event_key', 'state'], unique=False)
    op.create_index('ix_release_events_title', 'release_events', ['tracked_title_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('release_event_id', sa.BigInteger(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_revised', sa.Boolean(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_late', sa.Boolean(), nullable=False),
    sa.Column('gotify_message_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'claimed', 'sent', 'cancelled', 'expired')", name='ck_deliveries_status'),
    sa.ForeignKeyConstraint(['release_event_id'], ['release_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deliveries_due', 'notification_deliveries', ['status', 'due_at'], unique=False)
    op.create_index('ix_deliveries_event', 'notification_deliveries', ['release_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deliveries_event', table_name='notification_deliveries')
    op.drop_index('ix_deliveries_due', table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index('ix_release_events_title', table_name='release_events')
    op.drop_index('ix_release_events_current', table_name='release_events')
    op.drop_table('release_events')
    op.drop_index('ix_tracked_titles_status', table_name='tracked_titles')
    op.drop_index('ix_tracked_titles_refresh', table_name='tracked_titles')
    op.drop_table('tracked_titles')
    op.drop_index('ix_job_runs_name_started', table_name='job_runs')
    op.drop_table('job_runs')
    # ### end Alembic commands ###
